local_path:
  cifar_10_path: /home/ruiliu/Development/dataset/cifar-10
  imagenet_t10k_bin_path: /home/ruiliu/Development/dataset/imagenet10k.bin
  imagenet_t10k_img_path: /home/ruiliu/Development/dataset/imagenet10k
  imagenet_t10k_label_path: /home/ruiliu/Development/dataset/imagenet10k-label.txt
  imagenet_t1k_bin_path: /home/ruiliu/Development/dataset/imagenet1k.bin
  imagenet_t1k_img_path: /home/ruiliu/Development/dataset/imagenet1k
  imagenet_t1k_label_path: /home/ruiliu/Development/dataset/imagenet1k-label.txt
  mnist_train_img_path: /home/ruiliu/Development/dataset/mnist-train-images.idx3-ubyte
  mnist_train_label_path: /home/ruiliu/Development/dataset/mnist-train-labels.idx1-ubyte
  mnist_t10k_img_path: /home/ruiliu/Development/dataset/mnist-t10k-images.idx3-ubyte
  mnist_t10k_label_path: /home/ruiliu/Development/dataset/mnist-t10k-labels.idx1-ubyte
  profile_path: /home/ruiliu/Development/mtml-tf/profile-result

roscoe_path:
  cifar_10_path: /tank/local/ruiliu/dataset/cifar-10
  imagenet_t10k_bin_path: /tank/local/ruiliu/dataset/imagenet10k.bin
  imagenet_t10k_img_path: /tank/local/ruiliu/dataset/imagenet10k
  imagenet_t10k_label_path: /tank/local/ruiliu/dataset/imagenet10k-label.txt
  imagenet_t1k_bin_path: /tank/local/ruiliu/dataset/imagenet1k.bin
  imagenet_t1k_img_path: /tank/local/ruiliu/dataset/imagenet1k
  imagenet_t1k_label_path: /tank/local/ruiliu/dataset/imagenet1k-label.txt
  mnist_train_img_path: /tank/local/ruiliu/dataset/mnist-train-images.idx3-ubyte
  mnist_train_label_path: /tank/local/ruiliu/dataset/mnist-train-labels.idx1-ubyte
  mnist_t10k_img_path: /tank/local/ruiliu/dataset/mnist-t10k-images.idx3-ubyte
  mnist_t10k_label_path: /tank/local/ruiliu/dataset/mnist-t10k-labels.idx1-ubyte
  profile_path: /tank/local/ruiliu/mtml-tf/profile-result

hp_path:
  cifar_10_path: /home/user/Development/dataset/cifar-10
  imagenet_t10k_bin_path: /home/user/Development/dataset/imagenet10k.bin
  imagenet_t10k_img_path: /home/user/Development/dataset/imagenet10k
  imagenet_t10k_label_path: /home/user/Development/dataset/imagenet10k-label.txt
  imagenet_t1k_bin_path: /home/user/Development/dataset/imagenet1k.bin
  imagenet_t1k_img_path: /home/user/Development/dataset/imagenet1k
  imagenet_t1k_label_path: /home/user/Development/dataset/imagenet1k-label.txt
  mnist_train_img_path: /home/user/Development/dataset/mnist-train-images.idx3-ubyte
  mnist_train_label_path: /home/user/Development/dataset/mnist-train-labels.idx1-ubyte
  mnist_t10k_img_path: /home/user/Development/dataset/mnist-t10k-images.idx3-ubyte
  mnist_t10k_label_path: /home/user/Development/dataset/mnist-t10k-labels.idx1-ubyte
  profile_path: /home/user/Development/mtml-tf/profile-result

hyperparams_input:
  img_width_imagenet: 224
  img_height_imagenet: 224
  img_width_cifar10: 32
  img_height_cifar10: 32
  img_width_mnist: 28
  img_height_mnist: 28
  num_channel_rgb: 3
  num_channel_bw: 1
  num_class_imagenet: 1000
  num_class_cifar10: 10
  num_class_mnist: 10

hyperparams_single_train:
  num_epoch: 1
  random_seed: 10000
  model_type: densenet
  activation: relu
  optimizer: Adam
  batch_size: 32
  num_model_layer: 1
  learning_rate: 0.01
  record_marker: 2
  use_cpu: False
  use_raw_image: True
  measure_step: True
  use_tb_timeline: False

hyperparams_pack_train:
  num_epoch: 1
  random_seed: 10000
  packed_model_type:
    - mobilenet
    - mobilenet
  # activation: sigmoid, leaky_relu, tanh, relu
  activation:
    - relu
    - relu
  # optimizers: Adam, SGD, Adagrad, Momentum
  optimizer:
    - Adam
    - SGD
  num_model_layer:
    - 1
    - 1
  # if batch size are not all same, make batch_padding True
  batch_size:
    - 32
    - 32
  learning_rate:
    - 0.00001
    - 0.00001
  record_marker: 3
  batch_padding: False
  use_cpu: False
  use_raw_image: True
  same_input: True
  measure_step: True
  use_tb_timeline: False
