local_path:
  cifar_10_path: /home/ruiliu/Development/dataset/cifar-10
  imagenet_t10k_bin_path: /home/ruiliu/Development/dataset/imagenet10k.bin
  imagenet_t10k_img_path: /home/ruiliu/Development/dataset/imagenet10k
  imagenet_t10k_label_path: /home/ruiliu/Development/dataset/imagenet10k-label.txt
  imagenet_t1k_bin_path: /home/ruiliu/Development/dataset/imagenet1k.bin
  imagenet_t1k_img_path: /home/ruiliu/Development/dataset/imagenet1k
  imagenet_t1k_label_path: /home/ruiliu/Development/dataset/imagenet1k-label.txt
  mnist_train_img_path: /home/ruiliu/Development/dataset/mnist-train-images.idx3-ubyte
  mnist_train_label_path: /home/ruiliu/Development/dataset/mnist-train-labels.idx1-ubyte
  mnist_t10k_img_path: /home/ruiliu/Development/dataset/mnist-t10k-images.idx3-ubyte
  mnist_t10k_label_path: /home/ruiliu/Development/dataset/mnist-t10k-labels.idx1-ubyte
  profile_path: /home/ruiliu/Development/mtml-tf/profile-result

roscoe_path:
  cifar_10_path: /tank/local/ruiliu/dataset/cifar-10
  imagenet_t10k_bin_path: /tank/local/ruiliu/dataset/imagenet10k.bin
  imagenet_t10k_img_path: /tank/local/ruiliu/dataset/imagenet10k
  imagenet_t10k_label_path: /tank/local/ruiliu/dataset/imagenet10k-label.txt
  imagenet_t1k_bin_path: /tank/local/ruiliu/dataset/imagenet1k.bin
  imagenet_t1k_img_path: /tank/local/ruiliu/dataset/imagenet1k
  imagenet_t1k_label_path: /tank/local/ruiliu/dataset/imagenet1k-label.txt
  mnist_train_img_path: /tank/local/ruiliu/dataset/mnist-train-images.idx3-ubyte
  mnist_train_label_path: /tank/local/ruiliu/dataset/mnist-train-labels.idx1-ubyte
  mnist_t10k_img_path: /tank/local/ruiliu/dataset/mnist-t10k-images.idx3-ubyte
  mnist_t10k_label_path: /tank/local/ruiliu/dataset/mnist-t10k-labels.idx1-ubyte
  profile_path: /tank/local/ruiliu/mtml-tf/profile-result

hp_path:
  cifar_10_path: /home/user/Development/dataset/cifar-10
  imagenet_t10k_bin_path: /home/user/Development/dataset/imagenet10k.bin
  imagenet_t10k_img_path: /home/user/Development/dataset/imagenet10k
  imagenet_t10k_label_path: /home/user/Development/dataset/imagenet10k-label.txt
  imagenet_t1k_bin_path: /home/user/Development/dataset/imagenet1k.bin
  imagenet_t1k_img_path: /home/user/Development/dataset/imagenet1k
  imagenet_t1k_label_path: /home/user/Development/dataset/imagenet1k-label.txt
  mnist_train_img_path: /home/user/Development/dataset/mnist-train-images.idx3-ubyte
  mnist_train_label_path: /home/user/Development/dataset/mnist-train-labels.idx1-ubyte
  mnist_t10k_img_path: /home/user/Development/dataset/mnist-t10k-images.idx3-ubyte
  mnist_t10k_label_path: /home/user/Development/dataset/mnist-t10k-labels.idx1-ubyte
  profile_path: /home/user/Development/mtml-tf/profile-result

base_parameter:
  #img_width and img_height differs for dataset
  img_width: 224
  img_height: 224
  num_channel: 3
  #num_class differs for dataset
  num_class: 1000
  random_seed: 10000
  device_num: 2
  total_epochs: 100

device_placement_workload:
  # model: mobilenet, densenet, mlp, resnet, scn
  workload_model_type:
    - mobilenet
    - densenet
    - mlp
    - resnet
    - scn
  workload_model_num:
    - 3
    - 3
    - 2
    - 3
    - 2
  # activation: sigmoid, leaky_relu, tanh, relu
  activation:
    - relu
    - sigmoid
    - tanh
    - leaky_relu
  # optimizers: Adam, SGD, Adagrad, Momentum
  optimizer:
    - Adam
    - SGD
    - Adagrad
    - Momentum
  num_model_layer:
    - 1
  # if batch size are not all same, make batch_padding True
  batch_size:
    - 5
    - 10
    - 20
    - 32
    - 50
    - 64
    - 80
    - 100
    - 128
  learning_rate:
    - 0.00001
  record_marker: 3
  batch_padding: False
  use_cpu: False
  use_raw_image: True
  same_input: True
  measure_step: True
  use_tb_timeline: False

simple_device_placement:
  init_resource_conf: 1
  up_rate: 2
  discard_rate: 0.5

#the approximated memory usage peak in model training
model_memory_usage_imagenet (100MB):
  mobilenet_5: 5
  mobilenet_10: 8
  mobilenet_20: 13
  mobilenet_32: 20
  mobilenet_50: 30
  mobilenet_64: 38
  mobilenet_80: 47
  mobilenet_100: 58
  mobilenet_128: 74
  densenet_5: 20
  densenet_10: 30
  densenet_20: 40
  densenet_32: 60
  densenet_50: 80
  densenet_64: 100
  densenet_80: 120
  densenet_100: 140
  densenet_128: 180
  mlp_5: 26
  mlp_10: 26
  mlp_20: 20
  mlp_32: 20
  mlp_50: 26
  mlp_64: 26
  mlp_80: 26
  mlp_100: 26
  mlp_128: 21
  resnet_5: 11
  resnet_10: 15
  resnet_20: 26
  resnet_32: 38
  resnet_50: 56
  resnet_64: 71
  resnet_80: 87
  resnet_100: 108
  resnet_128: 136
  scn_5: 6
  scn_10: 6
  scn_20: 6
  scn_32: 7
  scn_50: 8
  scn_64: 9
  scn_80: 9
  scn_100: 10
  scn_128: 12



