workload:
  workload_size: 40
  cv_light_ratio: 0.3
  cv_med_ratio: 0.3
  cv_heavy_ratio: 0.4
  nlp_light_ratio: 0.3
  nlp_med_ratio: 0.3
  nlp_heavy_ratio: 0.4

objective:
  convergence_ratio: 0.6
  accuracy_ratio: 0.2
  runtime_ratio: 0.2

num_gpu: 4
random_seed: 99

# unit of slot: second
running_slot: 150