workload:
  workload_size: 40
  cv_light_ratio: 0.3
  cv_med_ratio: 0.3
  cv_heavy_ratio: 0.4
  nlp_light_ratio: 0.3
  nlp_med_ratio: 0.3
  nlp_heavy_ratio: 0.4

deadline:
  half_ddl_ratio: 0.1
  one_ddl_ratio: 0.2
  three_ddl_ratio: 0.3
  ten_ddl_ratio: 0.3
  day_ddl_ratio: 0.1

objective:
  convergence_ratio: 0.4
  accuracy_ratio: 0.2
  runtime_ratio: 0.1
  deadline_ratio: 0.3

num_gpu: 4
random_seed: 10000

# unit of slot: second
running_slot: 900