dlt_workload:
  workload_size: 40
  residual_ratio: 0.3
  mobile_ratio: 0.1
  lstm_ratio: 0.2
  bert_ratio: 0.1
  others_ratio: 0.3

objective:
  convergence_ratio: 0.6
  accuracy_ratio: 0.2
  runtime_ratio: 0.2

num_gpu: 4
random_seed: 42

# unit of slot: second
running_slot: 150
