hyperparams_input:
  img_width_imagenet: 224
  img_height_imagenet: 224
  img_width_cifar10: 32
  img_height_cifar10: 32
  img_width_mnist: 28
  img_height_mnist: 28
  num_channel_rgb: 3
  num_channel_bw: 1
  num_class_imagenet: 1000
  num_class_cifar10: 10
  num_class_mnist: 10


hyperparams_measure:
  random_seed: 10000
  batch_padding: False
  record_marker: 2
  use_cpu: False
  use_raw_image: True
  measure_step: True
  use_tb_timeline: False
  same_input: True
  available_gpu_num: 1
  available_cpu_num: 1

placement_schedule:
  # number of gpu devices for workload schedule
  gpu_device_num: 2
  # number of cpu devices for workload schedule
  cpu_device_num: 1
  # total number of jobs in a workload
  job_num: 100
  # total number of time slots for a workload
  time_slots_num: 48
  # time period of each slot (unit: seconds)
  slot_time_period: 180
  # training dataset
  train_dataset: cifar10
  # total available model type
  model_type_set:
    - mobilenet
    - resnet
    - densenet
    - mlp
  batch_size_set:
    - 32
    - 50
    - 64
    - 100
    - 128
  optimizer_set:
    - Adam
    - SGD
    - Adagrad
    - Momentum
  learning_rate_set:
    - 0.01
    - 0.001
    - 0.0001
    - 0.00001
    - 0.000001
  activation_set:
    - relu
    - sigmoid
    - tanh
    - leaky_relu
  # highest_accuracy, lowest_accuracy, average_accuracy
  reward_function: average_accuracy


profile_concur_cpugpu_workload:
  cpu_model_num:
    - 6
  cpu_model_type:
    - mobilenet
  cpu_batch_size:
    - 32
  cpu_learning_rate:
    - 0.01
  cpu_activation:
    - relu
  cpu_optimizer:
    - Adam
  gpu_model_num:
    - 1
  gpu_model_type:
    - resnet
  gpu_batch_size:
    - 32
  gpu_learning_rate:
    - 0.01
  gpu_activation:
    - relu
  gpu_optimizer:
    - Adam



simple_placement:
  init_resource_conf: 1
  up_rate: 2
  discard_rate: 0.5


#the approximated memory usage peak in model training
model_memory_usage_imagenet (100MB):
  mobilenet_5: 5
  mobilenet_10: 8
  mobilenet_20: 13
  mobilenet_32: 20
  mobilenet_50: 30
  mobilenet_64: 38
  mobilenet_80: 47
  mobilenet_100: 58
  mobilenet_128: 74
  densenet_5: 20
  densenet_10: 30
  densenet_20: 40
  densenet_32: 60
  densenet_50: 80
  densenet_64: 100
  densenet_80: 120
  densenet_100: 140
  densenet_128: 180
  mlp_5: 26
  mlp_10: 26
  mlp_20: 20
  mlp_32: 20
  mlp_50: 26
  mlp_64: 26
  mlp_80: 26
  mlp_100: 26
  mlp_128: 21
  resnet_5: 11
  resnet_10: 15
  resnet_20: 26
  resnet_32: 38
  resnet_50: 56
  resnet_64: 71
  resnet_80: 87
  resnet_100: 108
  resnet_128: 136
  scn_5: 6
  scn_10: 6
  scn_20: 6
  scn_32: 7
  scn_50: 8
  scn_64: 9
  scn_80: 9
  scn_100: 10
  scn_128: 12
