dlt_workload:
  workload_size: 40
  cv_light_ratio: 0.3
  cv_med_ratio: 0.3
  cv_heavy_ratio: 0.2
  nlp_light_ratio: 0.05
  nlp_med_ratio: 0.05
  nlp_heavy_ratio: 0.1

cv_workload:
  workload_size: 40
  light_ratio: 0.3
  med_ratio: 0.3
  heavy_ratio: 0.4

nlp_workload:
  workload_size: 40
  light_ratio: 0.3
  med_ratio: 0.3
  heavy_ratio: 0.4

objective:
  convergence_ratio: 0.6
  accuracy_ratio: 0.2
  runtime_ratio: 0.2

num_gpu: 4
random_seed: 42

# unit of slot: second
running_slot: 150
